In [116]:
import pandas as pd
import numpy as np

In [117]:
data_ori = pd.read_csv("train.csv")
summit_ori = pd.read_csv("test.csv")

In [118]:
data_ori.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
Loan_ID              614 non-null object
Gender               601 non-null object
Married              611 non-null object
Dependents           599 non-null object
Education            614 non-null object
Self_Employed        582 non-null object
ApplicantIncome      614 non-null int64
CoapplicantIncome    614 non-null float64
LoanAmount           592 non-null float64
Loan_Amount_Term     600 non-null float64
Credit_History       564 non-null float64
Property_Area        614 non-null object
Loan_Status          614 non-null object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.4+ KB


In [119]:
summit_ori.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
Loan_ID              367 non-null object
Gender               356 non-null object
Married              367 non-null object
Dependents           357 non-null object
Education            367 non-null object
Self_Employed        344 non-null object
ApplicantIncome      367 non-null int64
CoapplicantIncome    367 non-null int64
LoanAmount           362 non-null float64
Loan_Amount_Term     361 non-null float64
Credit_History       338 non-null float64
Property_Area        367 non-null object
dtypes: float64(3), int64(2), object(7)
memory usage: 34.5+ KB


In [120]:
data_ori.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [121]:
summit_ori.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       367.000000         367.000000  362.000000        361.000000   
mean       4805.599455        1569.577657  136.132597        342.537396   
std        4910.685399        2334.232099   61.366652         65.156643   
min           0.000000           0.000000   28.000000          6.000000   
25%        2864.000000           0.000000  100.250000        360.000000   
50%        3786.000000        1025.000000  125.000000        360.000000   
75%        5060.000000        2430.500000  158.000000        360.000000   
max       72529.000000       24000.000000  550.000000        480.000000   

       Credit_History  
count      338.000000  
mean         0.825444  
std          0.380150  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [122]:
# Revisión de Valores Nulos:

In [123]:
data_ori.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [124]:
summit_ori.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [125]:
data = data_ori.copy()
summit = summit_ori.copy()

In [126]:
# Revisión de Outliers:

In [127]:
def calcular_percentiles(lista):
    c = [0,5,10,20,30,40,50,60,70,80,90,92.5,95,97.5,99,99.9,100]
    matrix = pd.concat([pd.DataFrame(c),
           pd.DataFrame(np.percentile(lista.dropna(),c))],
           axis = 1)
    matrix.columns = ["percentile","valor"]
    return(matrix)

In [128]:
calcular_percentiles(lista = data["ApplicantIncome"]).T

0        1       2       3       4       5       6       7   \
percentile    0.0     5.00    10.0    20.0    30.0    40.0    50.0    60.0   
valor       150.0  1897.55  2216.1  2605.4  3050.4  3406.8  3812.5  4343.6   

                8       9       10         11       12         13        14  \
percentile    70.0    80.0    90.0     92.500     95.0     97.500     99.00   
valor       5185.6  6252.4  9459.9  10752.075  14583.0  17948.875  32540.41   

                   15       16  
percentile     99.900    100.0  
valor       70172.581  81000.0

In [129]:
calcular_percentiles(lista = data["CoapplicantIncome"]).T

0    1     2     3     4     5       6       7       8       9   \
percentile  0.0  5.0  10.0  20.0  30.0  40.0    50.0    60.0    70.0    80.0   
valor       0.0  0.0   0.0   0.0   0.0   0.0  1188.5  1689.6  2083.0  2535.0   

                10        11      12        13       14        15       16  
percentile    90.0    92.500    95.0    97.500    99.00     99.90    100.0  
valor       3782.2  4300.025  4997.4  6666.675  8895.89  36867.21  41667.0

In [130]:
calcular_percentiles(lista = data["LoanAmount"]).T

0     1     2     3      4      5      6      7      8      9   \
percentile  0.0   5.0  10.0  20.0   30.0   40.0   50.0   60.0   70.0   80.0   
valor       9.0  56.0  71.0  95.0  108.0  116.0  128.0  137.0  158.0  182.0   

               10     11     12     13      14      15     16  
percentile   90.0   92.5   95.0   97.5   99.00   99.90  100.0  
valor       235.8  259.0  297.8  384.5  496.36  670.45  700.0

In [131]:
calcular_percentiles(lista = data["Loan_Amount_Term"]).T

0      1      2      3      4      5      6      7      8   \
percentile   0.0    5.0   10.0   20.0   30.0   40.0   50.0   60.0   70.0   
valor       12.0  180.0  294.0  360.0  360.0  360.0  360.0  360.0  360.0   

               9      10     11     12     13     14     15     16  
percentile   80.0   90.0   92.5   95.0   97.5   99.0   99.9  100.0  
valor       360.0  360.0  360.0  360.0  363.0  480.0  480.0  480.0

In [132]:
data_ori.head(20)

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0   LP001002    Male      No          0      Graduate            No   
1   LP001003    Male     Yes          1      Graduate            No   
2   LP001005    Male     Yes          0      Graduate           Yes   
3   LP001006    Male     Yes          0  Not Graduate            No   
4   LP001008    Male      No          0      Graduate            No   
5   LP001011    Male     Yes          2      Graduate           Yes   
6   LP001013    Male     Yes          0  Not Graduate            No   
7   LP001014    Male     Yes         3+      Graduate            No   
8   LP001018    Male     Yes          2      Graduate            No   
9   LP001020    Male     Yes          1      Graduate            No   
10  LP001024    Male     Yes          2      Graduate            No   
11  LP001027    Male     Yes          2      Graduate           NaN   
12  LP001028    Male     Yes          2      Graduate            No   
13  LP001029    Male      No          0      Graduate            No   
14  LP001030    Male     Yes          2      Graduate            No   
15  LP001032    Male      No          0      Graduate            No   
16  LP001034    Male      No          1  Not Graduate            No   
17  LP001036  Female      No          0      Graduate            No   
18  LP001038    Male     Yes          0  Not Graduate            No   
19  LP001041    Male     Yes          0      Graduate           NaN   

    ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0              5849                0.0         NaN             360.0   
1              4583             1508.0       128.0             360.0   
2              3000                0.0        66.0             360.0   
3              2583             2358.0       120.0             360.0   
4              6000                0.0       141.0             360.0   
5              5417             4196.0       267.0             360.0   
6              2333             1516.0        95.0             360.0   
7              3036             2504.0       158.0             360.0   
8              4006             1526.0       168.0             360.0   
9             12841            10968.0       349.0             360.0   
10             3200              700.0        70.0             360.0   
11             2500             1840.0       109.0             360.0   
12             3073             8106.0       200.0             360.0   
13             1853             2840.0       114.0             360.0   
14             1299             1086.0        17.0             120.0   
15             4950                0.0       125.0             360.0   
16             3596                0.0       100.0             240.0   
17             3510                0.0        76.0             360.0   
18             4887                0.0       133.0             360.0   
19             2600             3500.0       115.0               NaN   

    Credit_History Property_Area Loan_Status  
0              1.0         Urban           Y  
1              1.0         Rural           N  
2              1.0         Urban           Y  
3              1.0         Urban           Y  
4              1.0         Urban           Y  
5              1.0         Urban           Y  
6              1.0         Urban           Y  
7              0.0     Semiurban           N  
8              1.0         Urban           Y  
9              1.0     Semiurban           N  
10             1.0         Urban           Y  
11             1.0         Urban           Y  
12             1.0         Urban           Y  
13             1.0         Rural           N  
14             1.0         Urban           Y  
15             1.0         Urban           Y  
16             NaN         Urban           Y  
17             0.0         Urban           N  
18             1.0         Rural           N  
19             1.0         Urban           Y

In [133]:
# Transformar campos:

In [134]:
new_data = pd.DataFrame()
new_summit = pd.DataFrame()

In [135]:
# Gender
dicc_gender = {'Female':0, 'Male': 1}
new_data['Gender'] = data_ori[:]['Gender'].map(dicc_gender)
new_summit['Gender'] = summit_ori[:]['Gender'].map(dicc_gender)

In [136]:
# Married
dicc_married = {'No':0, 'Yes': 1}
new_data['Married'] = data_ori[:]['Married'].map(dicc_married)
new_summit['Married'] = summit_ori[:]['Married'].map(dicc_married)

In [137]:
# Dependents
dicc_dependents = {'0':0, '1': 1, '2': 2, '3+': 3}
new_data['Dependents'] = data_ori[:]['Dependents'].map(dicc_dependents)
new_summit['Dependents'] = summit_ori[:]['Dependents'].map(dicc_dependents)

In [138]:
# Education
dicc_education = {'Not Graduate':0, 'Graduate': 1}
new_data['Education'] = data_ori[:]['Education'].map(dicc_education)
new_summit['Education'] = summit_ori[:]['Education'].map(dicc_education)

In [139]:
# Self_Employed
dicc_self_employed = {'No':0, 'Yes': 1}
new_data['Self_Employed'] = data_ori[:]['Self_Employed'].map(dicc_self_employed)
new_summit['Self_Employed'] = summit_ori[:]['Self_Employed'].map(dicc_self_employed)

In [140]:
# ApplicantIncome
new_data['ApplicantIncome'] = data_ori['ApplicantIncome']
new_summit['ApplicantIncome'] = summit_ori['ApplicantIncome']

In [141]:
# CoapplicantIncome
new_data['CoapplicantIncome'] = data_ori['CoapplicantIncome']
new_summit['CoapplicantIncome'] = summit_ori['CoapplicantIncome']

In [142]:
# LoanAmount
new_data['LoanAmount'] = data_ori['LoanAmount']
new_summit['LoanAmount'] = summit_ori['LoanAmount']

In [143]:
# Loan_Amount_Term
new_data['Loan_Amount_Term'] = data_ori['Loan_Amount_Term']
new_summit['Loan_Amount_Term'] = summit_ori['Loan_Amount_Term']

In [144]:
# Credit_History
new_data['Credit_History'] = data_ori['Credit_History']
new_summit['Credit_History'] = summit_ori['Credit_History']

In [145]:
# Property_Area
Property_Area_dummies_d = pd.get_dummies(data_ori['Property_Area'], prefix = 'Area')
new_data = pd.concat([new_data,Property_Area_dummies_d],axis=1)

Property_Area_dummies_s = pd.get_dummies(summit_ori['Property_Area'], prefix = 'Area')
new_summit = pd.concat([new_summit,Property_Area_dummies_s],axis=1)

In [146]:
# Loan_Status
dicc_self_loan = {'N':0, 'Y': 1}
new_data['Loan_Status'] = data_ori[:]['Loan_Status'].map(dicc_self_loan)

In [147]:
new_data.describe()

Gender     Married  Dependents   Education  Self_Employed  \
count  601.000000  611.000000  599.000000  614.000000     582.000000   
mean     0.813644    0.651391    0.762938    0.781759       0.140893   
std      0.389718    0.476920    1.015216    0.413389       0.348211   
min      0.000000    0.000000    0.000000    0.000000       0.000000   
25%      1.000000    0.000000    0.000000    1.000000       0.000000   
50%      1.000000    1.000000    0.000000    1.000000       0.000000   
75%      1.000000    1.000000    2.000000    1.000000       0.000000   
max      1.000000    1.000000    3.000000    1.000000       1.000000   

       ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  Area_Rural  Area_Semiurban  Area_Urban  Loan_Status  
count      564.000000  614.000000      614.000000  614.000000   614.000000  
mean         0.842199    0.291531        0.379479    0.328990     0.687296  
std          0.364878    0.454838        0.485653    0.470229     0.463973  
min          0.000000    0.000000        0.000000    0.000000     0.000000  
25%          1.000000    0.000000        0.000000    0.000000     0.000000  
50%          1.000000    0.000000        0.000000    0.000000     1.000000  
75%          1.000000    1.000000        1.000000    1.000000     1.000000  
max          1.000000    1.000000        1.000000    1.000000     1.000000

In [148]:
new_data.describe()

Gender     Married  Dependents   Education  Self_Employed  \
count  601.000000  611.000000  599.000000  614.000000     582.000000   
mean     0.813644    0.651391    0.762938    0.781759       0.140893   
std      0.389718    0.476920    1.015216    0.413389       0.348211   
min      0.000000    0.000000    0.000000    0.000000       0.000000   
25%      1.000000    0.000000    0.000000    1.000000       0.000000   
50%      1.000000    1.000000    0.000000    1.000000       0.000000   
75%      1.000000    1.000000    2.000000    1.000000       0.000000   
max      1.000000    1.000000    3.000000    1.000000       1.000000   

       ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  Area_Rural  Area_Semiurban  Area_Urban  Loan_Status  
count      564.000000  614.000000      614.000000  614.000000   614.000000  
mean         0.842199    0.291531        0.379479    0.328990     0.687296  
std          0.364878    0.454838        0.485653    0.470229     0.463973  
min          0.000000    0.000000        0.000000    0.000000     0.000000  
25%          1.000000    0.000000        0.000000    0.000000     0.000000  
50%          1.000000    0.000000        0.000000    0.000000     1.000000  
75%          1.000000    1.000000        1.000000    1.000000     1.000000  
max          1.000000    1.000000        1.000000    1.000000     1.000000

In [149]:
# Tramiento de oultiers:

In [35]:
## ApplicantIncome
temp_top = np.percentile(new_data["ApplicantIncome"],95)
new_data.loc[new_data["ApplicantIncome"]>temp_top,"ApplicantIncome"] = temp_top
new_summit.loc[new_summit["ApplicantIncome"]>temp_top,"ApplicantIncome"] = temp_top

In [36]:
## ApplicantIncome
temp_top = np.percentile(new_data["CoapplicantIncome"],99)
new_data.loc[new_data["CoapplicantIncome"]>temp_top,"CoapplicantIncome"] = temp_top
new_summit.loc[new_summit["CoapplicantIncome"]>temp_top,"CoapplicantIncome"] = temp_top

In [150]:
data = new_data.copy()
summit = new_summit.copy()

In [151]:
# Imputar nulos:
features_imputar_moda = ['Gender',
 'Married',
 'Dependents',
 'Education',
 'Self_Employed',
 'Credit_History']

features_imputar_median = ['Loan_Amount_Term',
 'ApplicantIncome',
 'CoapplicantIncome',
 'LoanAmount']

In [152]:
## Moda
from scipy.stats import mode
for feature in features_imputar_moda:
    moda = mode(data[feature]).mode[0]
    data[feature].fillna(moda, inplace=True)
    summit[feature].fillna(moda, inplace=True)

In [153]:
## Median
for feature in features_imputar_median:
    median = data[feature].median()
    data[feature].fillna(median, inplace=True)
    summit[feature].fillna(median, inplace=True)

In [154]:
list(data_ori.columns)

['Loan_ID',
 'Gender',
 'Married',
 'Dependents',
 'Education',
 'Self_Employed',
 'ApplicantIncome',
 'CoapplicantIncome',
 'LoanAmount',
 'Loan_Amount_Term',
 'Credit_History',
 'Property_Area',
 'Loan_Status']

In [155]:
data.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Area_Rural           0
Area_Semiurban       0
Area_Urban           0
Loan_Status          0
dtype: int64

In [156]:
summit.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Area_Rural           0
Area_Semiurban       0
Area_Urban           0
dtype: int64

In [157]:
list(data.columns)

['Gender',
 'Married',
 'Dependents',
 'Education',
 'Self_Employed',
 'ApplicantIncome',
 'CoapplicantIncome',
 'LoanAmount',
 'Loan_Amount_Term',
 'Credit_History',
 'Area_Rural',
 'Area_Semiurban',
 'Area_Urban',
 'Loan_Status']

In [158]:
# Creación de Nuevas Variables:
data["Income_Sum"] = data["ApplicantIncome"] + data["CoapplicantIncome"]
summit["Income_Sum"] = summit["ApplicantIncome"] + summit["CoapplicantIncome"]

In [159]:
data["porc_I1_t1"] = (1000*data["LoanAmount"]/data["Loan_Amount_Term"])/(data["ApplicantIncome"])
data["porc_I1_t2"] = (1000*data["LoanAmount"]/data["Loan_Amount_Term"])/(data["ApplicantIncome"]/(1+data["Dependents"]))

data["porc_I2_t1"] = (1000*data["LoanAmount"]/data["Loan_Amount_Term"])/(data["Income_Sum"])
data["porc_I2_t2"] = (1000*data["LoanAmount"]/data["Loan_Amount_Term"])/(data["Income_Sum"]/(1+data["Dependents"]))

summit["porc_I1_t1"] = (1000*summit["LoanAmount"]/summit["Loan_Amount_Term"])/(summit["ApplicantIncome"])
summit["porc_I1_t2"] = (1000*summit["LoanAmount"]/summit["Loan_Amount_Term"])/(summit["ApplicantIncome"]/(1+summit["Dependents"]))

summit["porc_I2_t1"] = (1000*summit["LoanAmount"]/summit["Loan_Amount_Term"])/(summit["Income_Sum"])
summit["porc_I2_t2"] = (1000*summit["LoanAmount"]/summit["Loan_Amount_Term"])/(summit["Income_Sum"]/(1+summit["Dependents"]))

In [160]:
data.head(20)

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0      1.0      0.0         0.0          1            0.0             5849   
1      1.0      1.0         1.0          1            0.0             4583   
2      1.0      1.0         0.0          1            1.0             3000   
3      1.0      1.0         0.0          0            0.0             2583   
4      1.0      0.0         0.0          1            0.0             6000   
5      1.0      1.0         2.0          1            1.0             5417   
6      1.0      1.0         0.0          0            0.0             2333   
7      1.0      1.0         3.0          1            0.0             3036   
8      1.0      1.0         2.0          1            0.0             4006   
9      1.0      1.0         1.0          1            0.0            12841   
10     1.0      1.0         2.0          1            0.0             3200   
11     1.0      1.0         2.0          1            0.0             2500   
12     1.0      1.0         2.0          1            0.0             3073   
13     1.0      0.0         0.0          1            0.0             1853   
14     1.0      1.0         2.0          1            0.0             1299   
15     1.0      0.0         0.0          1            0.0             4950   
16     1.0      0.0         1.0          0            0.0             3596   
17     0.0      0.0         0.0          1            0.0             3510   
18     1.0      1.0         0.0          0            0.0             4887   
19     1.0      1.0         0.0          1            0.0             2600   

    CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                 0.0       128.0             360.0             1.0   
1              1508.0       128.0             360.0             1.0   
2                 0.0        66.0             360.0             1.0   
3              2358.0       120.0             360.0             1.0   
4                 0.0       141.0             360.0             1.0   
5              4196.0       267.0             360.0             1.0   
6              1516.0        95.0             360.0             1.0   
7              2504.0       158.0             360.0             0.0   
8              1526.0       168.0             360.0             1.0   
9             10968.0       349.0             360.0             1.0   
10              700.0        70.0             360.0             1.0   
11             1840.0       109.0             360.0             1.0   
12             8106.0       200.0             360.0             1.0   
13             2840.0       114.0             360.0             1.0   
14             1086.0        17.0             120.0             1.0   
15                0.0       125.0             360.0             1.0   
16                0.0       100.0             240.0             1.0   
17                0.0        76.0             360.0             0.0   
18                0.0       133.0             360.0             1.0   
19             3500.0       115.0             360.0             1.0   

    Area_Rural  Area_Semiurban  Area_Urban  Loan_Status  Income_Sum  \
0            0               0           1            1      5849.0   
1            1               0           0            0      6091.0   
2            0               0           1            1      3000.0   
3            0               0           1            1      4941.0   
4            0               0           1            1      6000.0   
5            0               0           1            1      9613.0   
6            0               0           1            1      3849.0   
7            0               1           0            0      5540.0   
8            0               0           1            1      5532.0   
9            0               1           0            0     23809.0   
10           0               0           1            1      3900.0   
11           0       

In [161]:
list(data.columns)

['Gender',
 'Married',
 'Dependents',
 'Education',
 'Self_Employed',
 'ApplicantIncome',
 'CoapplicantIncome',
 'LoanAmount',
 'Loan_Amount_Term',
 'Credit_History',
 'Area_Rural',
 'Area_Semiurban',
 'Area_Urban',
 'Loan_Status',
 'Income_Sum',
 'porc_I1_t1',
 'porc_I1_t2',
 'porc_I2_t1',
 'porc_I2_t2']

In [162]:
# Dataset
features_to_model = ['Gender',
 'Married',
 'Dependents',
 'Education',
 'Self_Employed',
 'ApplicantIncome',
 'CoapplicantIncome',
 'LoanAmount',
 'Loan_Amount_Term',
 'Credit_History',
 'Area_Rural',
 'Area_Semiurban',
 'Area_Urban',
 'Income_Sum',
 'porc_I1_t1',
 'porc_I1_t2',
 'porc_I2_t1',
 'porc_I2_t2']

In [163]:
#características y target
X = data[features_to_model]
y = data['Loan_Status']

X_summit = summit[features_to_model].copy()

In [164]:
from sklearn import model_selection
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, train_size = 0.70, random_state=0)
print(len(X_train), len(y_train), len(X_test), len(y_test))

429 429 185 185


In [102]:
# Modelamiento
RandomForestClassifier()

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [165]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators = 100, random_state = 0, n_jobs = 3, max_depth = 4)

from sklearn.ensemble import GradientBoostingClassifier
gbm = GradientBoostingClassifier(n_estimators = 20 , min_samples_leaf = 15, random_state = 0, max_depth = 5, subsample = 0.8)

from sklearn.linear_model import LogisticRegression
etc = LogisticRegression(max_iter =100, n_jobs = 3, random_state = 0) 

In [166]:
forest = forest.fit(X_train, y_train)
gbm = gbm.fit(X_train, y_train)
etc = etc.fit(X_train, y_train)

In [167]:
temp_atr = pd.concat([pd.DataFrame({'atributo':list(X.columns)}),
                      pd.DataFrame({'importancia':list(gbm.feature_importances_)})], axis = 1)
ranking_features = temp_atr[['atributo','importancia']].sort_values('importancia', ascending = False).reset_index(drop = True)
ranking_features

atributo  importancia
0      Credit_History     0.384200
1          Income_Sum     0.095583
2          porc_I2_t1     0.093020
3     ApplicantIncome     0.090287
4          LoanAmount     0.087875
5          porc_I1_t2     0.061817
6          porc_I2_t2     0.050337
7          porc_I1_t1     0.039022
8   CoapplicantIncome     0.029176
9    Loan_Amount_Term     0.019250
10         Area_Rural     0.018088
11          Education     0.013018
12     Area_Semiurban     0.010882
13      Self_Employed     0.007447
14            Married     0.000000
15         Area_Urban     0.000000
16         Dependents     0.000000
17             Gender     0.000000

In [168]:
# Train
y_pred_train_forest = forest.predict(X_train)
y_pred_train_gbm = gbm.predict(X_train)
y_pred_train_etc = etc.predict(X_train)

# Test
y_pred_test_forest = forest.predict(X_test)
y_pred_test_gbm = gbm.predict(X_test)
y_pred_test_etc = etc.predict(X_test)

In [169]:
y_pred_train = np.round((y_pred_train_forest + y_pred_train_gbm + y_pred_train_etc)/3,0)
y_pred_test = np.round((y_pred_test_forest + y_pred_test_gbm + y_pred_test_etc)/3,0)

In [170]:
from sklearn import metrics as mt

print("Train")
cm_train = mt.confusion_matrix(y_train,y_pred_train)
print(cm_train)
print("Test")
cm_test = mt.confusion_matrix(y_test,y_pred_test)
print(cm_test)

Train
[[ 69  72]
 [  5 283]]
Test
[[ 21  30]
 [  3 131]]


In [171]:
accuracy_train = mt.accuracy_score(y_train.astype('int'),y_pred_train.astype('int'))
print ("Accuracy Train: ", accuracy_train*100)

accuracy_test = mt.accuracy_score(y_test.astype('int'),y_pred_test.astype('int'))
print ("Accuracy Test : ", accuracy_test*100)


Accuracy Train:  82.0512820513
Accuracy Test :  82.1621621622


In [189]:
# To summit
#y_pred_summit_forest = forest.predict(X_summit)

#X_summit.describe()

X_summit[["porc_I1_t1"]].nan()

AttributeError: 'DataFrame' object has no attribute 'nan'

In [111]:
y_pred_summit_forest = forest.predict(X_summit)
y_pred_summit_gbm = gbm.predict(X_summit)
y_pred_summit_etc = etc.predict(X_summit)

y_pred_sumit = np.round((y_pred_summit_forest + y_pred_summit_gbm + y_pred_summit_etc)/3,0)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [105]:
summit_final = pd.concat( [summit_ori.ix[:,'Loan_ID'] , pd.DataFrame(y_pred_sumit,columns = ['Loan_Status'] )], axis = 1)

In [106]:
dicc_target = {1:'Y', 0: 'N'}
summit_final['Loan_Status'] = summit_final[:]['Loan_Status'].map(dicc_target)

In [107]:
summit_final.head()

Loan_ID Loan_Status
0  LP001015           Y
1  LP001022           Y
2  LP001031           Y
3  LP001035           Y
4  LP001051           Y

In [108]:
summit_final.to_csv("Summit_4.csv", index = False )

In [ ]:
# Función General To Models:

In [346]:
def modelar_evaluar(model, X_train, X_test, y_test, titulo):
    print("\n=============== ", titulo, " ===============")
    # Entrenar
    model = model.fit(X_train, y_train)

    # Predecir
    ## Train
    y_pred_train = model.predict(X_train)
    y_pred_proba_train = model.predict_proba(X_train)
    
    ## Test
    y_pred_test = model.predict(X_test)
    y_pred_proba_test = model.predict_proba(X_test)

    from sklearn import metrics as mt

    cm_train = mt.confusion_matrix(y_train,y_pred_train)
    print("Matriz de Confusión: Train")
    print(cm_train)
    
    cm_test = mt.confusion_matrix(y_test,y_pred_test)
    print("\nMatriz de Confusión: Test")
    print(cm_test)

    accuracy_train = mt.accuracy_score(y_train.astype('int'),y_pred_train.astype('int'))
    accuracy_test = mt.accuracy_score(y_test.astype('int'),y_pred_test.astype('int'))
    print ("\nAccuracy Train: ", accuracy_train*100)
    print ("Accuracy Test : ", accuracy_test*100)
    
    roc_train = mt.roc_auc_score(y_train.astype('int'),y_pred_proba_train[:,1])
    roc_test = mt.roc_auc_score(y_test.astype('int'),y_pred_proba_test[:,1])
    print ("\nROC Train: ", roc_train*100)
    print ("ROC Test : ", roc_test*100)   
    

### A. Random Forest

In [359]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators = 100, random_state = 100, n_jobs = 3, min_samples_leaf = 16)
modelar_evaluar(forest, X_train, X_test, y_test, titulo = "Random Forest")


===============  Random Forest  ===============
Matriz de Confusión: Train
[[ 63  78]
 [  5 283]]

Matriz de Confusión: Test
[[ 21  30]
 [  2 132]]

Accuracy Train:  80.6526806527
Accuracy Test :  82.7027027027

ROC Train:  90.5412726556
ROC Test :  80.3043605502


### B. ExtraTreesClassifier

In [363]:
from sklearn.ensemble import ExtraTreesClassifier
etc = ExtraTreesClassifier(n_estimators = 100, random_state = 0, n_jobs = 3, min_samples_leaf = 10)
modelar_evaluar(etc, X_train, X_test, y_test, titulo = "ExtraTreesClassifier")


===============  ExtraTreesClassifier  ===============
Matriz de Confusión: Train
[[ 61  80]
 [  5 283]]

Matriz de Confusión: Test
[[ 21  30]
 [  2 132]]

Accuracy Train:  80.1864801865
Accuracy Test :  82.7027027027

ROC Train:  84.889676911
ROC Test :  80.1872988001


### B. LogisticRegression

In [351]:
from sklearn.linear_model import LogisticRegression
rlog = LogisticRegression(max_iter =200, n_jobs = 3, random_state = 0) 
modelar_evaluar(rlog, X_train, X_test, y_test, titulo = "LogisticRegression")


===============  LogisticRegression  ===============
Matriz de Confusión: Train
[[ 63  78]
 [  6 282]]

Matriz de Confusión: Test
[[ 21  30]
 [  2 132]]

Accuracy Train:  80.4195804196
Accuracy Test :  82.7027027027

ROC Train:  79.4621749409
ROC Test :  77.7875329236
